bwf_achats:
    resource: "@BWFAchatsBundle/Resources/config/routing.yml"
    prefix:   /

bwf_site:
    resource: "@BWFSiteBundle/Resources/config/routing.yml"
    prefix:   /

bwf_formations:
    resource: "@BWFFormationsBundle/Resources/config/routing.yml"
    prefix:   /

bwf_video:
    resource: "@BWFVideoBundle/Resources/config/routing.yml"
    prefix:   /

bwf_articles:
    resource: "@BWFArticlesBundle/Resources/config/routing.yml"
    prefix:   /

