parameters:
#    bwf_video.example.class: BWF\VideosBundle\Example

services:
#    bwf_video.example:
#        class: %bwf_video.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
